### ISSUE TITLE
ColorClickerPreference crash

### ISSUE THREAD

**Issue by MenosGrante** [garretyoder/Colorful#9]
I am using Colorful and want to allow users choose themes from settings. Added `ColorClickerPreference` to my preferences file and getting crash when trying to open settings now.

Log
```
FATAL EXCEPTION: main
Process: com.itemstudio.castro, PID: 22833
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itemstudio.castro/com.itemstudio.castro.settings.SettingsActivity}: java.lang.ClassCastException: org.polaric.colorful.ColorPickerPreference cannot be cast to android.preference.Preference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6176)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

Caused by: java.lang.ClassCastException: org.polaric.colorful.ColorPickerPreference cannot be cast to android.preference.Preference
at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:104)
at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
at android.preference.GenericInflater.inflate(GenericInflater.java:327)
at android.preference.GenericInflater.inflate(GenericInflater.java:264)
at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:326)
at com.itemstudio.castro.settings.SettingsFragment.onCreate(SettingsFragment.java:23)
at android.app.Fragment.performCreate(Fragment.java:2336)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
at android.app.BackStackRecord.setLastIn(BackStackRecord.java:861)
at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:901)
at android.app.BackStackRecord.run(BackStackRecord.java:728)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
at android.app.FragmentController.execPendingActions(FragmentController.java:371)
at android.app.Activity.performStart(Activity.java:6695)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6176) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by garretyoder** [comment]
Are you using the support preferences or stock? Colorful relies on the Support preferences to maintain material design.

**Comment by MenosGrante** [comment]
I was using stock preferences, when changed to Support Preferences crash losed.
